version: '3.4'

services:
  sqlserver:
    container_name: payment.sqlserver
    image: microsoft/mssql-server-linux
    build: 
      context: ./container/sql
      dockerfile: ./Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DefaultPassword1
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    networks:
      - payment_network
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks: 
      - payment_network  
  RabbitMQ:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=logUser 
      - RABBITMQ_DEFAULT_PASS=logPwd 
      - RABBITMQ_DEFAULT_VHOST=PaymentLog
    ports:
      - "15672:15672"
      - "5672:5672"  
    networks:
      - payment_network
networks:
  payment_network:
    driver: bridge